// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMKTh5AlTO6MFhYh4CoRuc-DUs2DLhf0',
    appId: '1:312154719998:web:ff96606c47ce9fe780c7af',
    messagingSenderId: '312154719998',
    projectId: 'patientapp-fa8f4',
    authDomain: 'patientapp-fa8f4.firebaseapp.com',
    storageBucket: 'patientapp-fa8f4.firebasestorage.app',
    measurementId: 'G-T6W2DMGHED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFVga4Xm1cgy9aVT_kp5V0qEbd7NT2do',
    appId: '1:312154719998:android:756fc201bbeb770780c7af',
    messagingSenderId: '312154719998',
    projectId: 'patientapp-fa8f4',
    storageBucket: 'patientapp-fa8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChcVzCSOExpeJhTmPhSUEXWL0g9MQHhxw',
    appId: '1:312154719998:ios:32c6e18620b2787080c7af',
    messagingSenderId: '312154719998',
    projectId: 'patientapp-fa8f4',
    storageBucket: 'patientapp-fa8f4.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChcVzCSOExpeJhTmPhSUEXWL0g9MQHhxw',
    appId: '1:312154719998:ios:32c6e18620b2787080c7af',
    messagingSenderId: '312154719998',
    projectId: 'patientapp-fa8f4',
    storageBucket: 'patientapp-fa8f4.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMKTh5AlTO6MFhYh4CoRuc-DUs2DLhf0',
    appId: '1:312154719998:web:e761e96ea0ea119980c7af',
    messagingSenderId: '312154719998',
    projectId: 'patientapp-fa8f4',
    authDomain: 'patientapp-fa8f4.firebaseapp.com',
    storageBucket: 'patientapp-fa8f4.firebasestorage.app',
    measurementId: 'G-QQYRC03S46',
  );
}
